### ISSUE TITLE
Support for async insert

### ISSUE THREAD

**Issue by magurotuna** [ClickHouse/clickhouse.rs#65]
Hi, thanks for the effort to make clickhouse accessible from Rust!
It would be even greater to have a support for [async insert](https://clickhouse.com/docs/en/cloud/bestpractices/asynchronous-inserts) when inserting records with this crate.

**Comment by makorne** [comment]
> Hi, thanks for the effort to make clickhouse accessible from Rust! It would be even greater to have a support for [async insert](https://clickhouse.com/docs/en/cloud/bestpractices/asynchronous-inserts) when inserting records with this crate.

Hi!
Thank you for great pull.
I tried your async_insert branch.
But some normal queries got erros:

```
BadResponse(\"Code: 131. DB::Exception: Too large string size: 4080532305067419703. The maximum is: 1073741824. To increase the maximum, use setting format_binary_max_string_size: (at row 1)\\n: While executing BinaryRowInputFormat. (TOO_LARGE_STRING_SIZE) (version 23.4.2.11 (official build))\")",

BadResponse(\"Code: 33. DB::Exception: Cannot read all data. Bytes read: 1482. Bytes expected: 531664.: (at row 1)\\n: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 23.4.2.11 (official build))\")",
```

Any thinks?

**Comment by magurotuna** [comment]
@makorne Just to clarify, does your query work fine with non-async inserts?

**Comment by makorne** [comment]
Looks like it is my bad, I forgot to add :
`
#[serde(with = "serde_bytes")]  for  Vec<u8>,
`
Now will check.
Thank you for prompt answer!

**Comment by makorne** [comment]
> @makorne Just to clarify, does your query work fine with non-async inserts?

Issue solved only after return on non-async inserts. 
No BadResponse at all now.  
Although them was a lot even after `#[serde(with = "serde_bytes")]  for  Vec<u8>`,

**Comment by makorne** [comment]
> Now this issue has been fixed in the pull request
I test it now.
Looks - No BadResponse!!!

The perfect shot!

**Comment by slvrtrn** [comment]
Closing this, as `async_insert` is already supported via the client options. See [this example](https://github.com/ClickHouse/clickhouse.rs/blob/master/examples/async_insert.rs) on the main branch. 
Additionally, after #123, it will be possible to use `.with_option` not only with the `Client` instance but also with `insert`/`inserter` for a particular statement only (see [the not yet merged example from the branch](https://github.com/ClickHouse/clickhouse.rs/blob/c7cb05ebb65d55c709412b9799f442630ca7fde7/examples/clickhouse_settings.rs)).
