### ISSUE TITLE
Expose the binary format implementation

### ISSUE THREAD

**Issue by ilya-zlobintsev** [ClickHouse/clickhouse.rs#67]
Hi, I've noticed that this library has a serde-compatible implementation of the Clickhouse binary format, and I would like to use it in my project.
However, it is currently [in a private module](https://github.com/loyd/clickhouse.rs/blob/master/src/lib.rs#L44). Would it be possible to make it public?

**Comment by loyd** [comment]
Hello, it's slightly problematic because I don't want to make it server-compatible. Also, it uses specific signatures
```
pub(crate) fn deserialize_from<'de, T: Deserialize<'de>>(
    input: impl Buf,
    temp_buf: &'de mut [u8],
) -> Result<T> {
```
to support borrowed data.

Why do you need this ser/de code?

**Comment by ilya-zlobintsev** [comment]
I have a [UDF](https://clickhouse.com/docs/en/sql-reference/functions/udf) implement in Rust. It's currently communicating with Clickhouse using the `JSONEachRow` format, but I would like to use the binary format for better efficiency.
